logging:
  level:
    ROOT: info
    nl.appsource: debug
management:
  endpoints:
    access:
      default: unrestricted
    web:
      exposure:
        include: '*'
pseudoniemenservice:
  token-private-key: i4dfBykN5Fjw9p3ADxvpRUhpbFSXepRSOcRGuaiJ4iQ=
  identifier-private-key: b2RPRGh6aThiMmluVEpMWVVJM2lOTGlWekVCU2hDMEU=
